#!/usr/bin/env bash
# Vendor the three IC brand typefaces into the frontend bundle.
#
# Why self-hosted rather than a Google Fonts <link>, which is what the reference
# implementations (skills./mcp./docs.internetcomputer.org) use: this page takes
# card details. A stylesheet from fonts.googleapis.com plus font files from
# fonts.gstatic.com send every visitor's IP to a third party on page load, before
# any consent surface exists, on a property intended to be operated by the DFINITY
# Foundation. Self-hosting removes the request entirely. It renders identically —
# the same files, served from the asset canister.
#
# Latin subset only. The UI is English; the other subsets Google ships (cyrillic,
# greek, vietnamese, latin-ext) would roughly quadruple the byte count for glyphs
# nothing renders.
#
# Regenerate after changing the weight set:
#   scripts/fetch-fonts.sh
#
# Writes src/frontend/public/fonts/*.woff2 and src/frontend/src/fonts.css, both
# committed so a clean checkout builds without network access.
set -euo pipefail

cd "$(dirname "$0")/../src/frontend"

# The weights the brand guidelines specify, and no others:
#   Newsreader 380/400/500 + italics — editorial display and body
#   Inter 400/500/600              — UI chrome, eyebrows, nav, buttons
#   JetBrains Mono 400/500         — technical readouts, numerals, code
FAMILIES="family=Inter:wght@400;500;600\
&family=JetBrains+Mono:wght@400;500\
&family=Newsreader:ital,wght@0,380;0,400;0,500;1,380;1,400;1,500"

# A browser UA is required: with curl's default UA Google returns TTF rather than
# woff2, which is ~3x the bytes and loses the subsetting.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

mkdir -p public/fonts
TMP_CSS="$(mktemp)"
trap 'rm -f "$TMP_CSS"' EXIT

curl -fsS -A "$UA" "https://fonts.googleapis.com/css2?${FAMILIES}&display=swap" -o "$TMP_CSS"

# Emit "<slug> <url>" for the latin block of each face, then fetch each with curl
# (python's SSL trust store is not configured on macOS by default).
python3 - "$TMP_CSS" <<'PY' > /tmp/font-manifest.txt
import re, sys, pathlib
css = pathlib.Path(sys.argv[1]).read_text()
for subset, block in re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S):
    if subset != 'latin':
        continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1)
    wt = re.search(r'font-weight: (\d+)', block).group(1)
    st = re.search(r'font-style: (\w+)', block).group(1)
    url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
    slug = f"{fam.lower().replace(' ', '-')}-{wt}{'-italic' if st == 'italic' else ''}.woff2"
    print(f"{fam}\t{wt}\t{st}\t{slug}\t{url}")
PY

[ -s /tmp/font-manifest.txt ] || {
  echo "no latin faces parsed — did the Google Fonts CSS format change?" >&2
  exit 1
}

# Every one of these families ships as a VARIABLE font, and Google serves the same
# file for each requested weight — downloading per weight fetched identical bytes
# three times over (562 KB for what is really 197 KB). Collapse each family+style
# to one file declared with a weight RANGE, which is how a variable face is meant
# to be registered anyway.
rm -f public/fonts/*.woff2
python3 - <<'MANIFEST' > /tmp/font-faces.txt
import collections, pathlib, subprocess, sys

rows = [l.split('\t') for l in pathlib.Path('/tmp/font-manifest.txt').read_text().splitlines()]
groups = collections.defaultdict(list)
for fam, wt, st, slug, url in rows:
    groups[(fam, st)].append((int(wt), url))

for (fam, st), entries in sorted(groups.items()):
    entries.sort()
    urls = {u for _, u in entries}
    # One URL across every weight means one variable file. Anything else means
    # Google started serving static instances and collapsing would drop weights.
    assert len(urls) == 1, f'{fam} {st}: {len(urls)} distinct files, cannot collapse'
    slug = f"{fam.lower().replace(' ', '-')}{'-italic' if st == 'italic' else ''}.woff2"
    dest = pathlib.Path('public/fonts') / slug
    subprocess.run(['curl', '-fsS', entries[0][1], '-o', str(dest)], check=True)
    lo, hi = entries[0][0], entries[-1][0]
    weight = f'{lo}' if lo == hi else f'{lo} {hi}'
    print(f'  {fam:16} {st:7} {weight:9} {dest.stat().st_size / 1024:6.1f} KB', file=sys.stderr)
    print(f"@font-face {{\n  font-family: '{fam}';\n  font-style: {st};\n"
          f"  font-weight: {weight};\n  font-display: swap;\n"
          f"  src: url('/fonts/{slug}') format('woff2');\n}}\n")
MANIFEST

{
  echo "/* Self-hosted brand faces — generated by scripts/fetch-fonts.sh, do not edit."
  echo "   Latin subset only, one variable file per family and style."
  echo
  echo "   Self-hosted rather than fetched from Google so that no visitor IP reaches a"
  echo "   third party from a page that takes card details. */"
  echo
  cat /tmp/font-faces.txt
} > src/fonts.css

printf '\n  %s files, %s KB total\n' \
  "$(ls public/fonts/*.woff2 | wc -l | tr -d ' ')" \
  "$(echo "scale=1; $(cat public/fonts/*.woff2 | wc -c) / 1024" | bc)"
rm -f /tmp/font-manifest.txt /tmp/font-faces.txt
